### PR TITLE
adding dropdown menu home with install and features

### PR DESCRIPTION
**Pull request by paulo-valim**
Screenshot 2023-07-17 at 15 35 01
Screenshot 2023-07-17 at 15 35 06

### CODE REVIEW

**Comment by hugobarauna** [comment]
@paulo-valim looks good to me.

Is this only for the desktop version?

I noticed the mobile version menu looks like this:

image

**Comment by josevalim** [comment]
@hugobarauna do you have any suggestions on how to tackle this for mobile?

**Comment by paulo-valim** [comment]
@hugobarauna I didn't change the mobile. The solution I have in mind, which is to group Home / Install / Features into one button, doesn't make sense (We don't need another action from the user to show these three options). WDYT?

**Comment by hugobarauna** [comment]
@paulo-valim Yes, I agree there's no need for an extra click to see the subsection menu items from the home section.

There's probably some UX/UI pattern for mobile menus where there are sub-sections for a given main menu section, but that's not something that I have knowledge of.

That said, given we don't have many sub-menu items at this moment, I think we can move forward with the current solution you implemented. 👍

So, for me is :shipit:

**Review by josevalim — APPROVED** [review]

**Review by jonatanklosko — APPROVED** [review]

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
