### PR TITLE
leaning center section

### PR DESCRIPTION
**Pull request by paulo-valim**
Finished the 1st part of the section:

Screen Shot 2022-11-14 at 2 52 56 PM

### CODE REVIEW

**Comment by paulo-valim** [comment]
Screen Shot 2022-11-15 at 3 10 17 PM

@hugobarauna

**Comment by paulo-valim** [comment]
Screen Shot 2022-11-15 at 4 21 28 PM

Done! @hugobarauna

**Comment by hugobarauna** [comment]
@paulo-valim, it's ok for me. 👍

I didn't review the code (I don't know much about HTML and CSS); I just looked into the design implementation.

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
